---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: inline
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext);library(sf)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

##這我自己在試著把osmData下載下來
```{r}
download.file("C:/Users/tim85/Documents/GitHub/course-108-1-inclass-datavisualization/map1.osm",destfile = "map1.osm")
```
```{r}
st_layers("map1.osm")
```
```{r}
st_read("map1.osm",layer = "lines") -> sf_lala_lines
```

```{r}
st_read("map1.osm",layer = "points") -> sf_lala_points
```


```{r}
st_read("map1.osm",layer = "multipolygons") -> sf_lala_multipolygons
```

```{r}
sf_lala_points %>%
  ggplot()+geom_sf()+
  geom_sf(
    data = sf_lala_lines
  )  #做層疊上去
```



```{r}
sf_lala_lines %>%
  ggplot()+geom_sf() ->plot_lala_line
```



```{r}
sf_lala_multipolygons %>%
  ggplot()+geom_sf()
```













##課堂

```{r}
library(osmdata)
download.file("https://www.dropbox.com/s/wisgdb03j01js1r/map.osm?dl=1",
              destfile = "map.osm")
st_layers("map.osm")
```
```{r}
st_read("map.osm",layer="lines") -> sf_ntpu_lines
```


```{r}
sf_ntpu_lines %>%
  ggplot()+geom_sf()
```

```{r}
st_read("map.osm",layer="points") -> sf_ntpu_points
```

```{r}
sf_ntpu_points %>%
  ggplot()+geom_sf()
```


```{r}
st_read("map.osm",layer="multipolygons") -> sf_ntpu_multipoygons
```
```{r}
sf_ntpu_multipoygons %>%
  ggplot()+geom_sf()
```


## osm bbox


#opq
```{r}
# open pass query with bounding box
bbox_taipei <- opq(
  bbox = c(121.4616,25.1050,121.6058,24.9894) 
) 
```

```{r}
bbox_taipei %>%
  add_osm_feature(
    key="admin_level", value="5"
  ) %>%
  osmdata_sf() -> map_taipei_boundary

map_taipei_boundary  
```

```{r}
map_taipei_boundary$osm_multipolygons -> map_taipei #sf_class
```


```{r}
map_taipei %>%
  ggplot()+geom_sf()
```





```{r}
source("https://www.dropbox.com/s/8ndtvzqbdb4cb93/data_visulaization_pk.R?dl=1")
#老師創造的一個函數可以綁上面那些臭臭常常的名字用掉所以以後有這種情況的話可以source這一段就可以避免了
```



```{r}
download.file("https://www.dropbox.com/s/8ndtvzqbdb4cb93/data_visulaization_pk.R?dl=1",
              destfile = "data_visulaization_pk.R")
```

```{r}
map_taipei %>%
  osm_geom_rename() %>%
  ggplot()+
  geom_sf()
```

###chapter 6
```{r}
load(url("https://www.dropbox.com/s/r21jg0vxf77geu9/plot_tree.Rda?dl=1"))

plot_tree
```


```{r}
plot_tree +
  scale_x_continuous(
    sec.axis = dup_axis()
  ) 
```


#林亦齊作業範例
```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework6/graphData_homework6_021.Rda?raw=true"))
source("https://www.dropbox.com/s/0ydtqtxu5guy6i1/theme_lin.R?dl=1")

resume_df %>% 
  mutate(開始 = ymd(開始), 結束 = ymd(結束))  -> resume_df
```

```{r}
resume_df %>%
  ggplot(
    aes(x = 開始, y = 項目)) +    
  geom_text(
    aes(label = 名稱), size = 2.5) + 
  geom_segment(
    aes(
      xend = 結束, yend = 項目, color = 分類, size = 2, alpha = 1
      )
    ) +
  scale_x_date(
      breaks = seq(as.Date("2015-01-01"), as.Date("2020-01-01"), by="1 year"),
      labels = scales::date_format("%Y")
      )+
  labs(title = "Kuo, Shih-Jung  郭士榮", subtitle = "熱愛挑戰不設限、豐富國際經驗、在學三份實習") + 
  theme_lin() -> gg_basic

gg_basic
```


```{r}
gg_basic +
  facet_grid(分類~.) -> gg_facet

gg_facet
```

```{r}
gg_basic +
  facet_grid(
    rows=vars(分類)
    ) -> gg_facet

gg_facet
```

```{r}
gg_basic +
  facet_grid(分類~.,  scales = "free_y") -> gg_facet_free

gg_facet_free
```



#林書玉範例
```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework3/graphData_homework3_002.Rda?raw=true"))

graphData$sub_2015_city%>%
  arrange(desc(area), avg_nh)%>%
  mutate(city = forcats::fct_inorder(city)) -> df_eldercare
```







