---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: inline
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext);library(sf)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

```{r}
outer <-     
  rbind( # 外圍
    c(1,5),
    c(2,1),
    c(5,1),
    c(5,5),
    c(1,5)) # 必需自行輸入起點close it

hole <-
  rbind( # 洞
    c(2,4),
    c(3,2),
    c(4,3),
    c(2,4))  # 必需自行輸入起點close it
  
outer2 <- outer + 12
hole2 <- hole + 12
```

```{r}
sfg_county1 <- st_polygon(list(
  outer,hole
))
sfg_county2 <- st_polygon(list(
  outer2, hole2
))

sfc_county12column <- st_sfc(sfg_county1,sfg_county2)

sfc_county12column %>% ggplot+geom_sf()
```

```{r}
#各county的基本資訊 (同上一個圖 另一種作法)
df_county12 <- data.frame(
  name=c("county1","county2"),
  population=c(100,107)
)

#df添加geometry column
df_county12 %>%
  st_set_geometry(sfc_county12column) -> df_county12

df_county12 %>% names
```
```{r}
df_county12 %>%
  ggplot()+
  geom_sf()+
  geom_sf_text(
    aes(label=name,color=population)
  )
```

```{r}
dir.create("county12")
write_sf(df_county12,"county12/county12.shp")
```

```{r}
load(url("https://www.dropbox.com/s/uvco1te2kbs6o01/MRT_Taipei.Rda?dl=1"))
```

```{r}
sf_mrt_tpe %>%
  filter(
    stringr::str_detect(經過路線,"BL")
  ) ->
  sf_mrt_tpe_bl
```

```{r}
sf_mrt_tpe_bl %>%
  st_coordinates() %>%#這裡已經是矩陣了所以不用再rbind了
  st_linestring() -> sfg_mrt_bl
sfg_mrt_bl %>%
  ggplot()+geom_sf() #因為他沒有照排列來編數據 所以他連線連起來整亂跑
```

```{r}
sf_mrt_tpe_bl %>%
  mutate(
    站號=stringr::str_extract(
      經過路線,"(?<=(BL))[:digit:]+" #幫我在經過路線裡面有BL的後面有數字不管多少都幫我取(+號是全取的意思)
    ))%>%
  arrange(站號)->sf_mrt_tpe_bl #arrange是在依站號重新排序一次
```

```{r}
sf_mrt_tpe_bl %>%
  st_coordinates() %>%
  st_linestring() -> sfg_mrt_bl2 #捷運板南線的simple feature geometry
sfg_mrt_bl2 %>%
  ggplot()+
  geom_sf()
```
```{r}
df_mrt <- data.frame(
  linename="BL"
)
sfg_mrt
```

```{r}
#練習去load台灣得資料
```

