---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: inline
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```
```{r}
names(graphData$data) <- c("年份", "國民所得儲蓄投資毛額", "毛額")
```

```{r}
graphData$events <- 
  data.frame(
    start=c(2008,2013),
    end=c(2009,2014),
    ymin=c(-Inf,-Inf),
    ymax=c(Inf,Inf),
    name=c('次貸危機','歐債危機')
  )


graphData$originalDesign+
  geom_rect(
    data=graphData$events,
    mapping=aes(
      xmin=start,
      xmax=end,
      ymin=ymin,
      ymax=ymax
    ),
    inherit.aes = FALSE,alpha=0.2

  )
```



```{r}
startSalaryTopCat<- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/startSalaryTopCat.csv")

startSalaryTopCat$大職業別[2:7] %>% str_c(.,collapse="','")
startSalaryTopCat %>% filter(
  大職業別 %in% c('工業部門','礦業及土石採取業','製造業','電力及燃氣供應業','用水供應及污染整治業','營造業')
) -> startingSalary_industrial

graphList <- list()
startingSalary_industrial %>%
  filter(大職業別 !='工業部門') -> startingSalary_industrial_sub
startingSalary_industrial_sub %>%  
  ggplot(aes(x=大職業別))+
  geom_col(aes(y=`經常性薪資-薪資`))-> graphList$經常薪資_col0

graphList$經常薪資_col0
```

```{r}

```



```{r}
library(readr)
library100_102 <- read_csv("https://www.dropbox.com/s/wuo5o6l55lk68l6/library100_102.csv?dl=1")
```
```{r}
library100_102 %>%
  mutate(
    借閱日期=date(ymd_hms(借閱時間)),
    借閱年=year(借閱日期)
  ) -> library100_102

library100_102 %>%
  filter(
    借閱日期 %>% between(ymd("2014-09-01"),ymd("2015-06-30"))
  ) -> library2014  

library2014 %>%
  group_by(學號) %>%
  summarise(
    學院=last(學院),
    讀者年級=max(讀者年級)
  ) %>%
  ungroup() %>%
  mutate(
    讀者年級=as.factor(讀者年級)
    )-> library2014 
```

```{r}
library2014 %>%
  mutate(
    學院=reorder(學院,學號,length,order=T)
  ) -> library2014

library2014 %>% 
  ggplot()-> graphList$圖書_ggplotOnly

graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院), fill="#5A99B3", width=0.7
    )
```


```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,fill=as.factor(讀者年級)), width=0.7
  )
```


```{r}
set.seed(2019)
x <- rnorm(100)
head(x)
```

```{r}
ggplot2::cut_interval(x,n=8) -> x_interval
levels(x_interval)
```

```{r}
df_x <- data.frame(
  x=x,
  x_interval=x_interval
)

df_x %>%
  group_by(x_interval) %>%
  summarise(
    interval_count=n()
  ) %>%
  ungroup() %>% #View
  ggplot(aes(x=x_interval))+
  geom_col(
    aes(y=interval_count)
  )
```

