---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: inline
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext);library(sf)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```


```{r}
download.file("http://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=72874C55-884D-4CEA-B7D6-F60B0BE85AB0",
              destfile="tw.zip")
unzip("tw.zip",exdir="taiwan")
read_sf("C:/Users/tim85/Documents/GitHub/course-108-1-inclass-datavisualization/COUNTY_MOI_1080726.shp")-> sf_taiwan
```

```{r}
sf_taiwan %>%
  rmapshaper::ms_simplify() -> sf_taiwan_simplify
```

```{r}
sf_taiwan_simplify %>%
  st_crop(
    xmin=119, xmax=123,
    ymin=21, ymax=26
  ) %>%
  ggplot()+geom_sf()
```


```{r}
# 取出spData套件附的world data
data(world,package="spData")
class(world) # 已是sf object
```

```{r}
world %>% st_geometry() %>%
  ggplot()+geom_sf()
```




#5.7.3

```{r}
load(url("https://www.dropbox.com/s/elnvocol0nnkcc9/sf_northTaiwan.Rda?dl=1"))
```

```{r}
sf_northTaiwan %>%
  st_centroid(of_largest_polygon = T) ->
  sf_centroid_northTaiwan

sf_centroid_northTaiwan
```


#5.9練習

```{r}
load(url("https://www.dropbox.com/s/uvco1te2kbs6o01/MRT_Taipei.Rda?dl=1"))
```

```{r}
read_sf("C:/Users/tim85/Documents/GitHub/course-108-1-inclass-datavisualization/MARK_捷運車站_1080626.shp") -> abc
#這是練習下載shp用的 用上面那個老師整理好的資料練習就好
```

```{r}
sf_mrtStops_tpe %>%
  st_crs() -> sf_mrtStops_tpe_crs
sf_mrtStops_tpe_crs
```

```{r}
sf_mrtStops_tpe %>%
  filter(
    stringr::str_detect(經過路線,"BL")
  ) -> sf_mrtStops_tpe_BL
```

```{r}
sf_mrtStops_tpe_BL %>%
  mutate(
      站號=str_extract(經過路線,"(?<=(BL))[:digit:]+")
            ) %>%
  arrange(站號) -> sf_mrtStops_BL
```

```{r}
sf_northTaiwan %>%
  ggplot()+geom_sf()+
  geom_sf(
    data=sf_mrtStops_BL
  )+
  coord_sf(
    xlim=c(121.4,121.7),
    ylim=c(24.9,25.1)
  ) -> gg_tpe_mrt
gg_tpe_mrt
```

