---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: inline
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```


```{r}
df_gatherExample <- data.frame(
  country=c("A","B","C"),
  `1999`=c("0.7k","37k","212k"),
  `2000`=c("2k","80k","213k"),
  check.names = F
)
df_gatherExample
```


```{r}
gather(df_gatherExample,
       `1999`,`2000`,
       key="年份",value="人口") ->ddddd
```


```{r}
library(readr)
collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")
```



```{r}
library(readr)
df_taoyuanMarriage <- read_csv("https://data.tycg.gov.tw/opendata/datalist/datasetMeta/download?id=f95d1a33-ec56-44c5-a9ec-3afba8157e39&rid=fd2070ef-7431-4f9c-bc3a-82d7bfbcd2fb")
```

```{r echo=FALSE, message=TRUE, warning=TRUE, paged.print=TRUE}
df_taoyuanMarriage%>%
  gather(
    ends_with("月"),
    key = "月份",value = "對數"
  ) ->df_taoyuanMarriage_gather
df_taoyuanMarriage_gather 

```

```{r}
df_taoyuanMarriage_gather %>%
  gather(ends_with("月"), key = "月數", value = "對數") %>%
  group_by(月份區域別) %>%
  dplyr::summarise(最高峰月份 = which.max
```


```{r}
df_twbankExchangeRate <- read_csv("http://www.bot.com.tw/Govinfo/opendata/csv/151/20180101-20181231-FXCRT.csv")
```

```{r}
df_twbankExchangeRate %>%
  select(-即期賣出匯率) %>%
  spread(
    幣別,即期買入匯率
  ) -> df_twbankExchangeRate_spread
```

```{r}
df_twbankExchangeRate %>%
  mutate(
    幣別=as.factor(幣別),
    即期買入匯率=as.double(即期買入匯率),
    即期賣出匯率=as.double(即期賣出匯率),
    日期=lubridate::ymd(日期)
  ) -> aa_twbankExchangeRate
```



```{r}
library(readr); library(dplyr)
# 線上引入原始資料成字串向量
read_lines("http://www.taifex.com.tw/data_gov/taifex_open_data.asp?data_name=DailyForeignExchangeRates") ->
  originalLines

# 將字串由CP950編碼改成UTF8再讀成data frame data2
originalLines %>%
  iconv(from="CP950",to="UTF8") %>% 
  read_csv() -> data2
```

```{r}
library(readr)
X27b5594a385573df182ebb70880cdcbe <- read_csv("http://opendataap2.hl.gov.tw/./resource/files/2019-03-15/27b5594a385573df182ebb70880cdcbe.csv")
View(X27b5594a385573df182ebb70880cdcbe)

```

```{r}
library(readr)
subsetDataTWbank <- read_csv("https://www.dropbox.com/s/t8ulj3d7cgl8jh5/subsetDataTWbank.csv?dl=1")
```
```{r}
library(ggplot2)
ggplot(subsetDataTWbank)+
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )
```

```{r}
subsetDataTWbank %>%
  ggplot()+
  geom_point(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
    )+
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )
```



```{r}
subsetDataTWbank %>%
  gather(
    contains("定存"),
    key = "期數", value = "利率"
  )->subsetDataTWbank_gather
subsetDataTWbank_gather%>%
  ggplot() +
  geom_boxplot(
    aes(x=期數,y=利率,color=西元年月)
  )
```

```{r}
subsetDataTWbank_gather %>%
  ggplot()+
  geom_line(
    aes(x=西元年月,y=利率,color=期數)
  )
```


```{r}
subsetDataTWbank %>%
  ggplot()+
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`),
    color="red",
    alpha=0.2,
    size=2
  )
```



```{r}
subsetDataTWbank_gather$期數 %>% 
  as.factor %>% levels
```

```{r}
subsetDataTWbank %>%
  mutate(
    年月=年月 %>%
      stringr::str_extract_all("[:digit:]+") %>%
      purrr::map_chr(
                 function(x) {
                   x1=as.integer(x[[1]])+1911
                   x[[1]]=as.character(x1)
                                stringr::str_c(x,collapse="-")
                 }
                 ),
    年月日=stringr::str_c(年月,"01",sep="-"),
    西元年月日=lubridate::ymd(年月日)
  ) ->subsetDataTWbank_time
```

