---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: inline
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

```{r}
library(grDevices) # 不同顏色模型代碼的呈現及轉換
library(scales) # show_col()螢幕立即顯示顏色
library(colorspace) # 調色盤選擇及ggplot應用工具
library(shinyjs) # 支援套件
```



```{r}
choose_color()
```

```{r}
choose_palette(gui="shiny")
```

```{r}
colorspace::sequential_hcl(n = 7, h = c(300, 200), c = c(60, NA, 0), l = c(25, 95), power = c(0.7, 1.3), register = "myPalette")
```



```{r}
colorspace::qualitative_hcl(n = 7, h = c(146, 360), c = 88, l = 55, register = "newPalette")
```


```{r}
data.frame(
  x1 = factor(sample(c(1L,2L,3L),100,replace=T)),
  x2 = runif(100),
  y = runif(100),
  z1 = rnorm(100),
  z2 = factor(sample(letters[1:4],100,replace=T))
) -> df_example
df_example
```

```{r}
df_example %>%
  ggplot()+
  geom_boxplot(
    aes(x=x1,y=y,fill=z2)
  ) -> basicBoxplot
basicBoxplot
```



```{r}
basicBoxplot +
  scale_fill_discrete_sequential(palette = "myPalette",nmax = 5)
```


```{r}
basicBoxplot +
  scale_fill_discrete_qualitative(palette =  "newPalette",nmax= 5 )
```














```{r}
data.frame(
  x1 = factor(sample(c(1L,2L,3L),100,replace=T)),
  x2 = runif(100),
  y = runif(100),
  z1 = rnorm(100),
  z2 = factor(sample(letters[1:4],100,replace=T))
) -> df_example

df_example %>%
  ggplot()+
  geom_boxplot(
    aes(x=x1,y=y,fill=z2)
  ) -> basicBoxplot
basicBoxplot

colorspace::qualitative_hcl(n = 7, h = c(0, 360), c = 35, l = 85, register = "Custom-Palette")

basicBoxplot +
  scale_fill_discrete_qualitative(palette="Custom-Palette",nmax=5)
```






```{r}
df_example %>%
  ggplot()+
  geom_point(
    aes(x=x2,y=y,color=z1)
  ) -> basicScatterPlot
basicScatterPlot
```


```{r}
basicScatterPlot+ scale_fill_brewer(palette = "myPalette")
```




